"""Generate Word Quest's independently sourced 5,000-word capacity index.

Source: wordfreq 3.1.1. The generated data is a derived index that must retain
the attribution and CC BY-SA 4.0 terms recorded in ATTRIBUTION.md.
"""

from pathlib import Path
import json
from wordfreq import top_n_list, zipf_frequency


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "client" / "src" / "data" / "vocabulary.ts"


def is_usable_headword(word: str) -> bool:
    return word.isalpha() and word.islower() and 2 <= len(word) <= 24


def reference_band(rank: int) -> str:
    """A transparent app-learning band, based on frequency rank rather than CEFR."""
    if rank <= 350:
        return "A1"
    if rank <= 1000:
        return "A2"
    if rank <= 2000:
        return "B1"
    if rank <= 3200:
        return "B2"
    if rank <= 4300:
        return "C1"
    return "C2"


def main() -> None:
    candidates = top_n_list("en", 18000, wordlist="best")
    words: list[str] = []
    seen: set[str] = set()

    for candidate in candidates:
        word = candidate.strip().lower()
        if word in seen or not is_usable_headword(word):
            continue
        seen.add(word)
        words.append(word)
        if len(words) == 5000:
            break

    if len(words) != 5000:
        raise RuntimeError(f"Expected 5,000 usable headwords; found {len(words)}.")

    entries = []
    for rank, word in enumerate(words, start=1):
        entries.append(
            {
                "id": word,
                "word": word,
                "rank": rank,
                "referenceBand": reference_band(rank),
                "zipf": round(zipf_frequency(word, "en"), 2),
            }
        )

    serialized = json.dumps(entries, ensure_ascii=False, separators=(",", ":"))
    output = f'''/*
 * Word Quest style reminder: independent 5,000-word capacity index.
 * Generated by scripts/generate_word_index.py using wordfreq 3.1.1.
 * This is not an Oxford word list. See ATTRIBUTION.md and SOURCES_AND_DATA_POLICY.md.
 */
export type VocabularyEntry = {{
  id: string;
  word: string;
  rank: number;
  referenceBand: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
  zipf: number;
}};

const vocabularyData = `{serialized}`;

export const VOCABULARY_INDEX: VocabularyEntry[] = JSON.parse(vocabularyData) as VocabularyEntry[];

export const VOCABULARY_INDEX_SOURCE = {{
  label: "Independent English frequency index generated from wordfreq 3.1.1",
  version: "wordfreq 3.1.1",
  license: "CC BY-SA 4.0 for the generated data; see ATTRIBUTION.md",
  count: VOCABULARY_INDEX.length,
}} as const;
'''
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Wrote {len(entries)} entries to {OUTPUT}")


if __name__ == "__main__":
    main()
